samples/web/classicmodels/src/main/domain/Order.java
package main.domain;

import java.util.Date;

public class Order {

	private String code;
	private Date orderDate;
	private Date shippedDate;
	private String status;
	private String comments;

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getOrderDate() {
		return orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Date getShippedDate() {
		return shippedDate;
	}

	public void setShippedDate(Date shippedDate) {
		this.shippedDate = shippedDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}

samples/web/classicmodels/src/main/domain/OrderDetail.java
package main.domain;

public class OrderDetail {

	private String productName;
	private int quantity;
	private Double price;

	public Double getTotal() {
		return quantity * price;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

}

samples/web/classicmodels/src/main/domain/Product.java
package main.domain;

public class Product {

	private String productCode;
	private String productName;
	private double buyPrice;
	private int quantity;
	private String scale;
	private String vendor;
	
	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductCode() {
		return productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public double getBuyPrice() {
		return buyPrice;
	}

	public void setBuyPrice(double buyPrice) {
		this.buyPrice = buyPrice;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getScale() {
		return scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getVendor() {
		return vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Override
	public String toString() {
		return "Product [productCode=" + productCode + ", productName=" + productName + ", buyPrice=" + buyPrice
				+ ", quantity=" + quantity + ", scale=" + scale + ", vendor=" + vendor + "]";
	}

	
	
}

samples/web/classicmodels/src/main/AbstractServlet.java
package main;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.sql.DataSource;

public class AbstractServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	/**
	 * Load db connection pool defined in tomcat context.xml Connection pooling
	 * is amazing thing having predefined pool of connections. Once connection
	 * is closed, it is directly returned back in the pool so can be used from
	 * another thread.
	 */
	public void init(ServletConfig config) throws ServletException {
		InitialContext context;
		if(!ConnectionService.hasDataSource()) {
			try {
				context = new InitialContext();
				DataSource pool = (DataSource) context
						.lookup("java:comp/env/jdbc/classicmodels");
				if (pool == null)
					throw new ServletException(
							"Unknown DataSource '" + config.getServletContext().getInitParameter("poolName") + "'");
				ConnectionService.init(pool);
			} catch (NamingException e) {
				e.printStackTrace();
			}
		}
	}
	
}

samples/web/classicmodels/src/pages/OrdersServlet.java
package pages;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.BitSet;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import main.AbstractServlet;
import main.ConnectionService;
import main.converters.OrderConverter;
import main.converters.OrderDetailsConverter;
import main.converters.ProductConverter;

/**
 * Servlet implementation class OrdersServlet
 */
public class OrdersServlet extends AbstractServlet {
	private static final long serialVersionUID = 1L;

	public OrdersServlet() {
		super();
		// TODO Auto-generated constructor stub
	}

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		Connection con = ConnectionService.getConnection();
		
		String singleOrderParam = request.getParameter("uid");
		// check if we have to display all records, or just a single one.
		try {
			if(singleOrderParam != null) {
				ResultSet resultSet = con.createStatement().executeQuery("select * from orders where orderNumber='" + singleOrderParam + "'");
				request.setAttribute("order", new OrderConverter().convert(resultSet));
				resultSet = con.createStatement().executeQuery("select od.quantityOrdered, od.priceEach, p.productName, p.productVendor from orderdetails od INNER JOIN products p ON od.productCode=p.productCode where od.orderNumber='" + singleOrderParam + "'");
				request.setAttribute("results", new OrderDetailsConverter().convertAll(resultSet));
				request.setAttribute("uid", singleOrderParam);
				request.getRequestDispatcher("/WEB-INF/pages/orders_item.jsp").forward(request, response);
			} else {
				ResultSet resultSet = con.createStatement().executeQuery("select * from orders");
				request.setAttribute("results", new OrderConverter().convertAll(resultSet));
				request.getRequestDispatcher("/WEB-INF/pages/orders.jsp").forward(request, response);
			}
			
			con.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

samples/web/classicmodels/src/pages/ProductsServlet.java
package pages;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.BitSet;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import main.AbstractServlet;
import main.ConnectionService;
import main.converters.ProductConverter;

/**
 * Servlet implementation class ProductsServlet
 */
public class ProductsServlet extends AbstractServlet {
	private static final long serialVersionUID = 1L;

	public ProductsServlet() {
		super();
		// TODO Auto-generated constructor stub
	}

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		Connection con = ConnectionService.getConnection();
		
		String singleProductParam = request.getParameter("uid");
		// check if we have to display all records, or just a single one.
		try {
			if(singleProductParam != null) {
				ResultSet resultSet = con.createStatement().executeQuery("select * from products where productCode='" + singleProductParam + "'");
				request.setAttribute("result", new ProductConverter().convert(resultSet));
				request.setAttribute("uid", singleProductParam);
				request.getRequestDispatcher("/WEB-INF/pages/products_item.jsp").forward(request, response);
			} else {
				ResultSet resultSet = con.createStatement().executeQuery("select * from products");
				request.setAttribute("results", new ProductConverter().convertAll(resultSet));
				request.getRequestDispatcher("/WEB-INF/pages/products.jsp").forward(request, response);
			}
			con.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		
		
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

samples/web/classicmodels/WebContent/WEB-INF/pages/orders.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="format" %>
<%@ taglib tagdir="/WEB-INF/tags/template" prefix="template" %>
<%@ taglib tagdir="/WEB-INF/tags/common" prefix="common" %>

<template:template>
	<div class="container">
		
		<common:resultsheading type="Orders" />
		
		<table>
			<thead>
				<tR>
					<th>Number</th>
					<th>Order Date</th>
					<th>Shipped Date</th>
					<th>Status</th>
					<th>Comments</th>
					<th>View</th>
				</tR>
			</thead>

			<tbody>
				<c:forEach items="${results}" var="order">
					<tr>
						<td>${order.code}</td>
						<td>
							<format:formatDate value="${order.orderDate}" pattern="dd/MM/YYYY" />
						</td>
						<td>
							<format:formatDate value="${order.shippedDate}" pattern="dd/MM/YYYY" />
						</td>
						<td>${order.status}</td>
						<td>${order.comments}</td>
						<td><a href="${appPath}orders?uid=${order.code}">View</a></td>
					</tr>		
				</c:forEach>
			</tbody>
		</table>
	</div>
</template:template>

samples/web/classicmodels/WebContent/WEB-INF/pages/orders_item.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="format" %>
<%@ taglib tagdir="/WEB-INF/tags/template" prefix="template" %>
<%@ taglib tagdir="/WEB-INF/tags/common" prefix="common" %>

<template:template>
	<div class="container">
		
		<common:singleitemheading type="Order" uid="${uid}" returnUri="orders" />
		
		<h2>Order </h2>
		<table>
			<thead>
				<tR>
					<th>Number</th>
					<th>Order Date</th>
					<th>Shipped Date</th>
					<th>Status</th>
					<th>Comments</th>
				</tR>
			</thead>

			<tbody>
				<tr>
					<td>${order.code}</td>
					<td>
						<format:formatDate value="${order.orderDate}" pattern="dd/MM/YYYY" />
					</td>
					<td>
						<format:formatDate value="${order.shippedDate}" pattern="dd/MM/YYYY" />
					</td>
					<td>${order.status}</td>
					<td>${order.comments}</td>
				</tr>		
			</tbody>
		</table>
		
		<h2>Items </h2>
		<table>
			<thead>
				<tR>
					<th>Product Name</th>
					<th>Quantity</th>
					<th>Base Price</th>
					<th>Total</th>
				</tR>
			</thead>

			<tbody>
				<c:forEach items="${results}" var="orderDetail">
					<tr>
						<td>${orderDetail.productName}</td>
						<td>${orderDetail.quantity}</td>
						<td><format:formatNumber value="${orderDetail.price}" type="currency" /></td>
						<td><format:formatNumber value="${orderDetail.total}" type="currency" /></td>
					</tr>		
				</c:forEach>
			</tbody>
		</table>
	</div>
</template:template>

samples/web/classicmodels/WebContent/WEB-INF/pages/products.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="format" %>
<%@ taglib tagdir="/WEB-INF/tags/template" prefix="template" %>
<%@ taglib tagdir="/WEB-INF/tags/common" prefix="common" %>


<template:template>
	<div class="container">
		
		<common:resultsheading type="Products" />
		
		<table>
			<thead>
				<tR>
					<th>Code</th>
					<th>Name</th>
					<th>Quantity</th>
					<th>Buy Price</th>
					<th>Vendor</th>
					<th>Scale</th>
					<th>View</th>
				</tR>
			</thead>
				
			<tbody>
				<c:forEach items="${results}" var="product">
					<tr>
						<td>${product.productCode}</td>
						<td>${product.productName}</td>
						<td>${product.quantity}</td>
						<td><format:formatNumber value="${product.buyPrice}" type="currency" /></td>
						<td>${product.vendor}</td>
						<td>${product.scale}</td>
						<td><a href="${appPath}products?uid=${product.productCode}">View</a></td>
					</tr>		
				</c:forEach>
			</tbody>
		</table>
	</div>
</template:template>

samples/web/classicmodels/WebContent/WEB-INF/pages/products_item.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="format" %>
<%@ taglib tagdir="/WEB-INF/tags/template" prefix="template" %>
<%@ taglib tagdir="/WEB-INF/tags/common" prefix="common" %>

<template:template>
	<div class="container">
		
		<common:singleitemheading type="Product" uid="${uid}" returnUri="products" />
		
		<table>
			<thead>
				<tR>
					<th>Code</th>
					<th>Name</th>
					<th>Quantity</th>
					<th>Buy Price</th>
					<th>Vendor</th>
					<th>Scale</th>
				</tR>
			</thead>

			<tbody>
					<tr>
						<td>${result.productCode}</td>
						<td>${result.productName}</td>
						<td>${result.quantity}</td>
						<td><format:formatNumber value="${result.buyPrice}" type="currency" /></td>
						<td>${result.vendor}</td>
						<td>${result.scale}</td>
					</tr>		
			</tbody>
		</table>
	</div>
</template:template>